### ISSUE TITLE
[Question] Why two images?

### ISSUE THREAD

**Issue by lonix1** [Monogramm/docker-taiga#25] opened 2019-08-12 13:45 UTC
I'm curious why there was a need for multiple images. Most taiga-docker implementations are single image, with another for the database of course. The frontend is just a simple angular app, so what is the point of an image just for that?

Is it possible for me to combine these images into one, or would that require a major rewrite?

**Comment by madmath03** [comment] 2019-08-12 16:46
Hi @lonix1 ,

> I'm curious why there was a need for multiple images.

The reason is simple : **you should never use Docker for running several services in the same container**.
Of course it will work to have several services running in one container, it's just *not a good practice*.

The reason for this is that Docker was designed with micro-services architecture in mind, meaning that every docker container should have only one service running. The benefit of such an architecture is, among other, scalability.

Let's take Taiga for example : since the frontend is an angular application, once it is running in the browser, you will not interact a lot with the web server after that.
Imagine you have a million users using your Taiga instance, each of them doing about a thousand requests per hour. Your frontend service may be fine, the only interaction being with NGinx to redirect `/api` to the backend, but your backend will receive a lot of traffic, probably too much for only one container.
In this case, the solution is to scale your backend (add more containers), but not the frontend (or at least not as much).

If the Docker image contains both the frontend and backend, you will be using resources for several frontend (NGinx servers) that you don't need.
With a micro-service approach like we did in this repository, you can precisely scale the resources for your particular need. This is particularly interesting if you plan to use Docker Swarm or Kubernetes.

There is a lot of [documentation online](https://success.docker.com/article/mta-best-practices#whattoincludeinanimage) about this, so do not take my word for it 😉 

Another reason which is to easily decouple the backend from the frontend.
For instance, if you want to add your own custom theme to Taiga, you just need to create a new image for the frontend, not _rebuild_ the full app.

> Is it possible for me to combine these images into one, or would that require a major rewrite?

Yes, that would be a major rewrite 😅 

I do not suggest it, but if you really want to do that, I suggest you rather look at other docker images like [ajira86/docker-taig](https://github.com/ajira86/docker-taiga) or [benhutchins/docker-taiga](https://github.com/benhutchins/docker-taiga).

I'm going to close this issue, but feel free to add a comment if you have any other question.

**Closed as completed by madmath03** 2019-08-12 16:46 UTC
Labels: enhancement

**Comment by lonix1** [comment] 2019-08-12 16:55
Thanks for your thoughts.

I need to disagree on the single service though - docker was meant for a single logical service, so it's perfectly acceptable to have multiple services in one container if they are a single **logical** service. This is a point of dispute and there are many people who sit on both sides of the fence.

However, I agree with you in general - it's easier to scale microservices.

BUT... in this *particular* case, how many people will use the app? I don't think thousands, it's just an app used inside a company when building a product. For us there's just a few devs, so we prefer a single image.

If you are facebook, then I get it! But of course they're not using taiga! :laughing: 

I appreciate the effort you put into this, I copied many ideas into my own images. Thanks a lot!

**Comment by lonix1** [comment] 2019-08-12 16:56
I wish the taiga team would have an official image, then we wouldn't have to struggle with this. :angry: 

I spent so much time getting this to work... I'm sure you did too!
